"""M10 systemic cascade and collapse facts."""
from alembic import op
import sqlalchemy as sa
revision='m10_0013'; down_revision='m9_0012'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('systemic_scenarios',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('scenario_id',u,nullable=False),sa.Column('scenario_type',sa.Text,nullable=False),sa.Column('initial_nodes',sa.Integer,nullable=False),sa.Column('propagation_rate_pct',sa.Numeric(8,4),nullable=False),sa.Column('liquidity_threshold_minor',sa.BigInteger,nullable=False),sa.Column('severity',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','scenario_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("severity IN ('HIGH','CRITICAL')"),schema='resilience_v2')
 op.create_table('cascade_events',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('event_id',u,nullable=False),sa.Column('scenario_id',u,nullable=False),sa.Column('node_type',sa.Text,nullable=False),sa.Column('node_key',sa.Text,nullable=False),sa.Column('wave',sa.Integer,nullable=False),sa.Column('state',sa.Text,nullable=False),sa.Column('exposure_minor',sa.BigInteger,nullable=False),sa.PrimaryKeyConstraint('tenant_id','event_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.ForeignKeyConstraint(['tenant_id','scenario_id'],['resilience_v2.systemic_scenarios.tenant_id','resilience_v2.systemic_scenarios.scenario_id']),schema='resilience_v2')
 op.create_table('systemic_impacts',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('impact_id',u,nullable=False),sa.Column('metric_key',sa.Text,nullable=False),sa.Column('metric_value',sa.Numeric(20,6),nullable=False),sa.Column('unit',sa.Text,nullable=False),sa.Column('capacity_state',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','impact_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("capacity_state IN ('WITHIN_CAPACITY','STRESSED','EXCEEDED')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M10 downgrade disabled; rebuild disposable V2 database explicitly')
