"""M13 board intelligence and shadow-run readiness facts."""
from alembic import op
import sqlalchemy as sa
revision='m13_0016'; down_revision='m12_0015'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('board_briefings',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('briefing_id',u,nullable=False),sa.Column('headline',sa.Text,nullable=False),sa.Column('condition_class',sa.Text,nullable=False),sa.Column('decision_required',sa.Text,nullable=False),sa.Column('resilience_score',sa.Numeric(8,4),nullable=False),sa.Column('confidence_pct',sa.Numeric(8,4),nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','briefing_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),schema='resilience_v2')
 op.create_table('shadow_run_gates',sa.Column('tenant_id',u,nullable=False),sa.Column('gate_id',u,nullable=False),sa.Column('gate_key',sa.Text,nullable=False),sa.Column('result',sa.Text,nullable=False),sa.Column('boundary',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','gate_id'),sa.UniqueConstraint('tenant_id','gate_key'),sa.CheckConstraint("result IN ('PASS','FAIL','PENDING')"),schema='resilience_v2')
 op.create_table('executive_actions',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('action_id',u,nullable=False),sa.Column('action_type',sa.Text,nullable=False),sa.Column('owner_role',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.Column('rationale',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','action_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("status IN ('PROPOSED','APPROVED','DEFERRED')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M13 downgrade disabled; rebuild disposable V2 database explicitly')
