"""M16 sandbox gateway and settlement adapter facts."""
from alembic import op
import sqlalchemy as sa
revision='m16_0019'; down_revision='m15_0018'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('gateway_adapters',sa.Column('tenant_id',u,nullable=False),sa.Column('adapter_id',u,nullable=False),sa.Column('adapter_key',sa.Text,nullable=False),sa.Column('provider_type',sa.Text,nullable=False),sa.Column('contract_version',sa.Text,nullable=False),sa.Column('mode',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','adapter_id'),sa.UniqueConstraint('tenant_id','adapter_key'),sa.CheckConstraint("mode IN ('SANDBOX','SHADOW','LIVE')"),sa.CheckConstraint("status IN ('DRAFT','ACTIVE','RETIRED')"),schema='resilience_v2')
 op.create_table('settlement_batches',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('batch_id',u,nullable=False),sa.Column('adapter_id',u,nullable=False),sa.Column('window_key',sa.Text,nullable=False),sa.Column('record_count',sa.Integer,nullable=False),sa.Column('retry_count',sa.Integer,nullable=False),sa.Column('idempotency_state',sa.Text,nullable=False),sa.Column('reconciliation_state',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','batch_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.ForeignKeyConstraint(['tenant_id','adapter_id'],['resilience_v2.gateway_adapters.tenant_id','resilience_v2.gateway_adapters.adapter_id']),sa.CheckConstraint("idempotency_state IN ('NEW','REPLAY_SAFE','REJECTED')"),sa.CheckConstraint("reconciliation_state IN ('PENDING','MATCHED','EXCEPTION')"),schema='resilience_v2')
 op.create_table('adapter_records',sa.Column('tenant_id',u,nullable=False),sa.Column('batch_id',u,nullable=False),sa.Column('record_id',u,nullable=False),sa.Column('source_event_key',sa.Text,nullable=False),sa.Column('obligation_id',u,nullable=False),sa.Column('mapping_state',sa.Text,nullable=False),sa.Column('retry_of',sa.Text,nullable=True),sa.Column('evidence_ref',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','record_id'),sa.ForeignKeyConstraint(['tenant_id','batch_id'],['resilience_v2.settlement_batches.tenant_id','resilience_v2.settlement_batches.batch_id']),sa.ForeignKeyConstraint(['tenant_id','obligation_id'],['resilience_v2.settlement_obligations.tenant_id','resilience_v2.settlement_obligations.obligation_id']),sa.UniqueConstraint('tenant_id','source_event_key'),sa.CheckConstraint("mapping_state IN ('MAPPED','DUPLICATE','UNMAPPED')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M16 downgrade disabled; rebuild disposable V2 database explicitly')
