"""M17 financial cash-flow and liquidity facts."""
from alembic import op
import sqlalchemy as sa
revision='m17_0020'; down_revision='m16_0019'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('liquidity_scenarios',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('liquidity_scenario_id',u,nullable=False),sa.Column('scenario_type',sa.Text,nullable=False),sa.Column('starting_liquidity_minor',sa.BigInteger,nullable=False),sa.Column('inflow_shock_pct',sa.Numeric(8,4),nullable=False),sa.Column('outflow_shock_pct',sa.Numeric(8,4),nullable=False),sa.Column('funding_capacity_minor',sa.BigInteger,nullable=False),sa.PrimaryKeyConstraint('tenant_id','liquidity_scenario_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),schema='resilience_v2')
 op.create_table('cash_flow_observations',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('cash_flow_id',u,nullable=False),sa.Column('period_index',sa.Integer,nullable=False),sa.Column('inflow_minor',sa.BigInteger,nullable=False),sa.Column('outflow_minor',sa.BigInteger,nullable=False),sa.Column('net_flow_minor',sa.BigInteger,nullable=False),sa.Column('liquidity_balance_minor',sa.BigInteger,nullable=False),sa.Column('funding_source',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','cash_flow_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),schema='resilience_v2')
 op.create_table('liquidity_measures',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('measure_id',u,nullable=False),sa.Column('measure_key',sa.Text,nullable=False),sa.Column('measure_value',sa.Numeric(20,6),nullable=False),sa.Column('unit',sa.Text,nullable=False),sa.Column('liquidity_state',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','measure_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("liquidity_state IN ('ADEQUATE','TIGHT','SHORTFALL')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M17 downgrade disabled; rebuild disposable V2 database explicitly')
