"""M18 versioned regulatory regimes and remediation facts."""
from alembic import op
import sqlalchemy as sa
revision='m18_0021'; down_revision='m17_0020'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('regulatory_regimes',sa.Column('tenant_id',u,nullable=False),sa.Column('regime_id',u,nullable=False),sa.Column('jurisdiction',sa.Text,nullable=False),sa.Column('regulation_code',sa.Text,nullable=False),sa.Column('version',sa.Text,nullable=False),sa.Column('effective_from',sa.DateTime(timezone=True),nullable=False),sa.Column('effective_to',sa.DateTime(timezone=True),nullable=True),sa.Column('reserve_rate_pct',sa.Numeric(8,4),nullable=False),sa.Column('review_rate_pct',sa.Numeric(8,4),nullable=False),sa.Column('status',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','regime_id'),sa.UniqueConstraint('tenant_id','jurisdiction','regulation_code','version'),schema='resilience_v2')
 op.create_table('regulatory_transitions',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('transition_id',u,nullable=False),sa.Column('regime_id',u,nullable=False),sa.Column('from_version',sa.Text,nullable=False),sa.Column('to_version',sa.Text,nullable=False),sa.Column('transition_state',sa.Text,nullable=False),sa.Column('affected_count',sa.Integer,nullable=False),sa.Column('evidence_ref',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','transition_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),schema='resilience_v2')
 op.create_table('compliance_remediations',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('remediation_id',u,nullable=False),sa.Column('transition_id',u,nullable=False),sa.Column('action_type',sa.Text,nullable=False),sa.Column('target_scope',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.Column('completed_count',sa.Integer,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','remediation_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("status IN ('PLANNED','IN_PROGRESS','COMPLETE')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M18 downgrade disabled; rebuild disposable V2 database explicitly')

