"""M19 repeatable board intelligence pack facts."""
from alembic import op
import sqlalchemy as sa
revision='m19_0022'; down_revision='m18_0021'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('board_pack_runs',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('pack_id',u,nullable=False),sa.Column('pack_type',sa.Text,nullable=False),sa.Column('period_label',sa.Text,nullable=False),sa.Column('overall_class',sa.Text,nullable=False),sa.Column('resilience_score',sa.Numeric(8,4),nullable=False),sa.Column('confidence_pct',sa.Numeric(8,4),nullable=False),sa.Column('status',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','pack_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("status IN ('DRAFT','REVIEW','APPROVED','ARCHIVED')"),schema='resilience_v2')
 op.create_table('board_pack_sections',sa.Column('tenant_id',u,nullable=False),sa.Column('pack_id',u,nullable=False),sa.Column('section_id',u,nullable=False),sa.Column('section_key',sa.Text,nullable=False),sa.Column('headline',sa.Text,nullable=False),sa.Column('content',sa.Text,nullable=False),sa.Column('severity',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','section_id'),sa.ForeignKeyConstraint(['tenant_id','pack_id'],['resilience_v2.board_pack_runs.tenant_id','resilience_v2.board_pack_runs.pack_id']),sa.CheckConstraint("severity IN ('INFO','WATCH','HIGH','CRITICAL')"),schema='resilience_v2')
 op.create_table('board_pack_actions',sa.Column('tenant_id',u,nullable=False),sa.Column('pack_id',u,nullable=False),sa.Column('action_id',u,nullable=False),sa.Column('action_text',sa.Text,nullable=False),sa.Column('owner_role',sa.Text,nullable=False),sa.Column('priority',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','action_id'),sa.ForeignKeyConstraint(['tenant_id','pack_id'],['resilience_v2.board_pack_runs.tenant_id','resilience_v2.board_pack_runs.pack_id']),sa.CheckConstraint("priority IN ('NOW','NEXT','MONITOR')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M19 downgrade disabled; rebuild disposable V2 database explicitly')
