"""M1 durable domain and execution foundation."""
from alembic import op
import sqlalchemy as sa

revision = "m1_0002"
down_revision = "m0_0001"


def upgrade(profile, **kwargs):
    uuid = sa.UUID()
    def tenant():
        return sa.Column("tenant_id", uuid, nullable=False)
    op.create_table("tenants", sa.Column("tenant_id", uuid, primary_key=True), sa.Column("name", sa.Text, nullable=False), sa.Column("state", sa.Text, nullable=False), sa.CheckConstraint("state IN ('ACTIVE','DISABLED')"), schema="resilience_v2")
    op.create_table("actors", sa.Column("tenant_id", uuid, nullable=False), sa.Column("actor_id", uuid, nullable=False), sa.Column("display_name", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "actor_id"), sa.ForeignKeyConstraint(["tenant_id"], ["resilience_v2.tenants.tenant_id"]), schema="resilience_v2")
    op.create_table("experiments", tenant(), sa.Column("experiment_id", uuid, nullable=False), sa.Column("purpose", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "experiment_id"), sa.ForeignKeyConstraint(["tenant_id"], ["resilience_v2.tenants.tenant_id"]), schema="resilience_v2")
    op.create_table("runs", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("experiment_id", uuid, nullable=False), sa.Column("parent_tenant_id", uuid), sa.Column("parent_run_id", uuid), sa.Column("branch_role", sa.Text, nullable=False), sa.Column("status", sa.Text, nullable=False), sa.Column("seed", sa.BigInteger, nullable=False), sa.Column("code_hash", sa.Text, nullable=False), sa.Column("model_hash", sa.Text, nullable=False), sa.Column("input_hash", sa.Text, nullable=False), sa.Column("virtual_time", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "run_id"), sa.ForeignKeyConstraint(["tenant_id", "experiment_id"], ["resilience_v2.experiments.tenant_id", "resilience_v2.experiments.experiment_id"]), sa.ForeignKeyConstraint(["parent_tenant_id", "parent_run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.CheckConstraint("branch_role IN ('BASELINE','STRESS','INTERVENTION','CONTROL')"), sa.CheckConstraint("status IN ('DRAFT','VALIDATED','READY','RUNNING','COMPLETED','FAILED','CANCELLED')"), sa.CheckConstraint("seed >= 0"), schema="resilience_v2")
    op.create_table("run_stages", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("stage_key", sa.Text, nullable=False), sa.Column("generation", sa.Integer, nullable=False), sa.Column("state", sa.Text, nullable=False), sa.Column("input_digest", sa.Text), sa.Column("output_digest", sa.Text), sa.PrimaryKeyConstraint("tenant_id", "run_id", "stage_key", "generation"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.CheckConstraint("generation > 0"), schema="resilience_v2")
    op.create_table("checkpoints", tenant(), sa.Column("checkpoint_id", uuid, nullable=False), sa.Column("run_id", uuid, nullable=False), sa.Column("as_of", sa.DateTime(timezone=True), nullable=False), sa.Column("max_event_sequence", sa.BigInteger, nullable=False), sa.Column("state_hash", sa.Text, nullable=False), sa.Column("sealed", sa.Boolean, nullable=False, server_default=sa.false()), sa.PrimaryKeyConstraint("tenant_id", "checkpoint_id"), sa.UniqueConstraint("tenant_id", "run_id", "max_event_sequence"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.CheckConstraint("max_event_sequence >= 0"), schema="resilience_v2")
    op.create_table("transactions", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("transaction_id", uuid, nullable=False), sa.Column("business_key", sa.Text, nullable=False), sa.Column("merchant_key", sa.Text, nullable=False), sa.Column("amount_minor", sa.BigInteger, nullable=False), sa.Column("currency", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "transaction_id"), sa.UniqueConstraint("tenant_id", "run_id", "business_key"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.CheckConstraint("amount_minor > 0"), sa.CheckConstraint("currency = 'INR'"), schema="resilience_v2")
    op.create_table("settlement_obligations", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("obligation_id", uuid, nullable=False), sa.Column("business_key", sa.Text, nullable=False), sa.Column("transaction_id", uuid, nullable=False), sa.Column("merchant_key", sa.Text, nullable=False), sa.Column("gross_minor", sa.BigInteger, nullable=False), sa.Column("fee_minor", sa.BigInteger, nullable=False), sa.Column("tax_minor", sa.BigInteger, nullable=False), sa.Column("net_minor", sa.BigInteger, nullable=False), sa.Column("currency", sa.Text, nullable=False), sa.Column("due_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "obligation_id"), sa.UniqueConstraint("tenant_id", "run_id", "business_key"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "transaction_id"], ["resilience_v2.transactions.tenant_id", "resilience_v2.transactions.transaction_id"]), sa.CheckConstraint("gross_minor > 0 AND fee_minor >= 0 AND tax_minor >= 0 AND net_minor = gross_minor - fee_minor - tax_minor AND net_minor >= 0"), sa.CheckConstraint("currency = 'INR'"), schema="resilience_v2")
    op.create_table("run_events", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("event_id", uuid, nullable=False), sa.Column("event_sequence", sa.BigInteger, nullable=False), sa.Column("event_type", sa.Text, nullable=False), sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False), sa.Column("payload_hash", sa.Text, nullable=False), sa.Column("effect_key", sa.Text), sa.PrimaryKeyConstraint("tenant_id", "event_id"), sa.UniqueConstraint("tenant_id", "run_id", "event_sequence"), sa.UniqueConstraint("tenant_id", "run_id", "effect_key"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.CheckConstraint("event_sequence > 0"), schema="resilience_v2")
    op.create_table("commands", tenant(), sa.Column("command_id", uuid, nullable=False), sa.Column("actor_id", uuid, nullable=False), sa.Column("command_type", sa.Text, nullable=False), sa.Column("idempotency_key", sa.Text, nullable=False), sa.Column("payload_hash", sa.Text, nullable=False), sa.Column("state", sa.Text, nullable=False), sa.Column("result_ref", sa.Text), sa.PrimaryKeyConstraint("tenant_id", "command_id"), sa.UniqueConstraint("tenant_id", "idempotency_key"), sa.ForeignKeyConstraint(["tenant_id", "actor_id"], ["resilience_v2.actors.tenant_id", "resilience_v2.actors.actor_id"]), sa.CheckConstraint("state IN ('ACCEPTED','RUNNING','SUCCEEDED','FAILED','CONFLICT')"), schema="resilience_v2")
    op.create_table("jobs", tenant(), sa.Column("job_id", uuid, nullable=False), sa.Column("command_id", uuid, nullable=False), sa.Column("state", sa.Text, nullable=False), sa.Column("fencing_token", sa.BigInteger, nullable=False, server_default="0"), sa.Column("lease_expires_at", sa.DateTime(timezone=True)), sa.PrimaryKeyConstraint("tenant_id", "job_id"), sa.ForeignKeyConstraint(["tenant_id", "command_id"], ["resilience_v2.commands.tenant_id", "resilience_v2.commands.command_id"]), sa.CheckConstraint("state IN ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED')"), sa.CheckConstraint("fencing_token >= 0"), schema="resilience_v2")
    op.create_table("audit_events", tenant(), sa.Column("audit_id", uuid, nullable=False), sa.Column("actor_id", uuid), sa.Column("action", sa.Text, nullable=False), sa.Column("outcome", sa.Text, nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "audit_id"), sa.ForeignKeyConstraint(["tenant_id", "actor_id"], ["resilience_v2.actors.tenant_id", "resilience_v2.actors.actor_id"]), schema="resilience_v2")
    op.execute(sa.text("GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO " + profile.runtime_user))
    op.execute(sa.text("ALTER DEFAULT PRIVILEGES FOR ROLE " + profile.migration_user + " IN SCHEMA resilience_v2 GRANT SELECT, INSERT, UPDATE ON TABLES TO " + profile.runtime_user))


def downgrade(**kwargs):
    raise RuntimeError("M1 downgrade disabled; rebuild disposable V2 database explicitly")

