"""M20 production shadow-run readiness controls."""
from alembic import op
import sqlalchemy as sa
revision='m20_0023'; down_revision='m19_0022'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('shadow_run_plans',sa.Column('tenant_id',u,nullable=False),sa.Column('plan_id',u,nullable=False),sa.Column('plan_key',sa.Text,nullable=False),sa.Column('data_boundary',sa.Text,nullable=False),sa.Column('retention_days',sa.Integer,nullable=False),sa.Column('live_action_policy',sa.Text,nullable=False),sa.Column('rollback_policy',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','plan_id'),sa.UniqueConstraint('tenant_id','plan_key'),sa.CheckConstraint("live_action_policy='PROHIBITED'"),sa.CheckConstraint("status IN ('DRAFT','APPROVED','READY','CLOSED')"),schema='resilience_v2')
 op.create_table('shadow_run_controls',sa.Column('tenant_id',u,nullable=False),sa.Column('plan_id',u,nullable=False),sa.Column('control_id',u,nullable=False),sa.Column('control_key',sa.Text,nullable=False),sa.Column('control_type',sa.Text,nullable=False),sa.Column('owner_role',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.Column('evidence_ref',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','control_id'),sa.ForeignKeyConstraint(['tenant_id','plan_id'],['resilience_v2.shadow_run_plans.tenant_id','resilience_v2.shadow_run_plans.plan_id']),sa.UniqueConstraint('tenant_id','plan_id','control_key'),sa.CheckConstraint("status IN ('PASS','FAIL','PENDING')"),schema='resilience_v2')
 op.create_table('shadow_run_incidents',sa.Column('tenant_id',u,nullable=False),sa.Column('plan_id',u,nullable=False),sa.Column('incident_id',u,nullable=False),sa.Column('incident_type',sa.Text,nullable=False),sa.Column('severity',sa.Text,nullable=False),sa.Column('response_playbook',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','incident_id'),sa.ForeignKeyConstraint(['tenant_id','plan_id'],['resilience_v2.shadow_run_plans.tenant_id','resilience_v2.shadow_run_plans.plan_id']),sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')"),sa.CheckConstraint("status IN ('DEFINED','TESTED','OPEN','CLOSED')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"));op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M20 downgrade disabled; rebuild disposable V2 database explicitly')
