"""M2 deterministic fixture and branch facts."""
from alembic import op
import sqlalchemy as sa

revision = "m2_0005"
down_revision = "m1_0004"


def upgrade(profile, **kwargs):
    uuid = sa.UUID()
    def tenant(): return sa.Column("tenant_id", uuid, nullable=False)
    op.create_table("lineage_mappings", tenant(), sa.Column("child_run_id", uuid, nullable=False), sa.Column("child_entity_id", uuid, nullable=False), sa.Column("entity_type", sa.Text, nullable=False), sa.Column("source_run_id", uuid, nullable=False), sa.Column("source_entity_id", uuid, nullable=False), sa.Column("source_checkpoint_id", uuid, nullable=False), sa.Column("business_key", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "child_entity_id"), sa.ForeignKeyConstraint(["tenant_id", "child_run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "source_run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.UniqueConstraint("tenant_id", "child_run_id", "entity_type", "business_key"), schema="resilience_v2")
    op.create_table("payment_obligations", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("payment_obligation_id", uuid, nullable=False), sa.Column("transaction_id", uuid, nullable=False), sa.Column("amount_minor", sa.BigInteger, nullable=False), sa.Column("currency", sa.Text, nullable=False), sa.Column("due_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "payment_obligation_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "transaction_id"], ["resilience_v2.transactions.tenant_id", "resilience_v2.transactions.transaction_id"]), sa.CheckConstraint("amount_minor > 0 AND currency='INR'"), schema="resilience_v2")
    op.create_table("scheduled_actions", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("action_id", uuid, nullable=False), sa.Column("obligation_id", uuid, nullable=False), sa.Column("action_type", sa.Text, nullable=False), sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False), sa.Column("priority", sa.Integer, nullable=False), sa.Column("state", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "action_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "obligation_id"], ["resilience_v2.settlement_obligations.tenant_id", "resilience_v2.settlement_obligations.obligation_id"]), sa.UniqueConstraint("tenant_id", "run_id", "obligation_id", "action_type"), sa.CheckConstraint("state IN ('PENDING','CANCELLED','EXECUTED','HELD')"), schema="resilience_v2")
    op.create_table("scenario_applications", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("scenario_id", uuid, nullable=False), sa.Column("scenario_type", sa.Text, nullable=False), sa.Column("parameters_hash", sa.Text, nullable=False), sa.Column("target_digest", sa.Text, nullable=False), sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "scenario_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), schema="resilience_v2")
    op.create_table("scenario_effects", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("effect_id", uuid, nullable=False), sa.Column("scenario_id", uuid, nullable=False), sa.Column("obligation_id", uuid, nullable=False), sa.Column("before_state", sa.Text, nullable=False), sa.Column("after_state", sa.Text, nullable=False), sa.Column("effect_key", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "effect_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "scenario_id"], ["resilience_v2.scenario_applications.tenant_id", "resilience_v2.scenario_applications.scenario_id"]), sa.UniqueConstraint("tenant_id", "effect_key"), schema="resilience_v2")
    op.create_table("settlement_executions", tenant(), sa.Column("run_id", uuid, nullable=False), sa.Column("execution_id", uuid, nullable=False), sa.Column("obligation_id", uuid, nullable=False), sa.Column("amount_minor", sa.BigInteger, nullable=False), sa.Column("currency", sa.Text, nullable=False), sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("source_event_key", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "execution_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "obligation_id"], ["resilience_v2.settlement_obligations.tenant_id", "resilience_v2.settlement_obligations.obligation_id"]), sa.UniqueConstraint("tenant_id", "source_event_key"), sa.CheckConstraint("amount_minor > 0 AND currency='INR'"), schema="resilience_v2")
    op.create_table("settlement_allocations", tenant(), sa.Column("allocation_id", uuid, nullable=False), sa.Column("execution_id", uuid, nullable=False), sa.Column("obligation_id", uuid, nullable=False), sa.Column("amount_minor", sa.BigInteger, nullable=False), sa.Column("currency", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "allocation_id"), sa.ForeignKeyConstraint(["tenant_id", "execution_id"], ["resilience_v2.settlement_executions.tenant_id", "resilience_v2.settlement_executions.execution_id"]), sa.ForeignKeyConstraint(["tenant_id", "obligation_id"], ["resilience_v2.settlement_obligations.tenant_id", "resilience_v2.settlement_obligations.obligation_id"]), sa.UniqueConstraint("tenant_id", "execution_id", "obligation_id"), sa.CheckConstraint("amount_minor > 0 AND currency='INR'"), schema="resilience_v2")
    op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"))
    op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))


def downgrade(**kwargs):
    raise RuntimeError("M2 downgrade disabled; rebuild disposable V2 database explicitly")
