"""M5 operational governance, replay safety, and audit facts."""
from alembic import op
import sqlalchemy as sa

revision = "m5_0008"
down_revision = "m4_0007"

def upgrade(profile, **kwargs):
    uuid = sa.UUID()
    op.create_table("run_manifests", sa.Column("tenant_id", uuid, nullable=False), sa.Column("run_id", uuid, nullable=False), sa.Column("manifest_id", uuid, nullable=False), sa.Column("input_digest", sa.Text, nullable=False), sa.Column("code_digest", sa.Text, nullable=False), sa.Column("schema_revision", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "manifest_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.UniqueConstraint("tenant_id", "run_id"), schema="resilience_v2")
    op.create_table("intervention_approvals", sa.Column("tenant_id", uuid, nullable=False), sa.Column("run_id", uuid, nullable=False), sa.Column("approval_id", uuid, nullable=False), sa.Column("intervention_type", sa.Text, nullable=False), sa.Column("requested_by", uuid, nullable=False), sa.Column("approved_by", uuid, nullable=False), sa.Column("status", sa.Text, nullable=False), sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False), sa.Column("rationale", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "approval_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "requested_by"], ["resilience_v2.actors.tenant_id", "resilience_v2.actors.actor_id"]), sa.ForeignKeyConstraint(["tenant_id", "approved_by"], ["resilience_v2.actors.tenant_id", "resilience_v2.actors.actor_id"]), sa.CheckConstraint("status IN ('REQUESTED','APPROVED','REJECTED','EXECUTED')"), schema="resilience_v2")
    op.create_table("replay_keys", sa.Column("tenant_id", uuid, nullable=False), sa.Column("run_id", uuid, nullable=False), sa.Column("replay_key", sa.Text, nullable=False), sa.Column("operation_type", sa.Text, nullable=False), sa.Column("request_digest", sa.Text, nullable=False), sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False), sa.Column("result_digest", sa.Text, nullable=False), sa.PrimaryKeyConstraint("tenant_id", "replay_key"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), schema="resilience_v2")
    op.create_table("decision_records", sa.Column("tenant_id", uuid, nullable=False), sa.Column("run_id", uuid, nullable=False), sa.Column("decision_id", uuid, nullable=False), sa.Column("decision_type", sa.Text, nullable=False), sa.Column("decision", sa.Text, nullable=False), sa.Column("actor_id", uuid, nullable=False), sa.Column("evidence_refs", sa.JSON, nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "decision_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "actor_id"], ["resilience_v2.actors.tenant_id", "resilience_v2.actors.actor_id"]), schema="resilience_v2")
    op.create_table("feed_quality_incidents", sa.Column("tenant_id", uuid, nullable=False), sa.Column("run_id", uuid, nullable=False), sa.Column("incident_id", uuid, nullable=False), sa.Column("feed_id", uuid, nullable=False), sa.Column("severity", sa.Text, nullable=False), sa.Column("quality_state", sa.Text, nullable=False), sa.Column("reason", sa.Text, nullable=False), sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("tenant_id", "incident_id"), sa.ForeignKeyConstraint(["tenant_id", "run_id"], ["resilience_v2.runs.tenant_id", "resilience_v2.runs.run_id"]), sa.ForeignKeyConstraint(["tenant_id", "feed_id"], ["resilience_v2.feed_manifests.tenant_id", "resilience_v2.feed_manifests.feed_id"]), sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')"), sa.CheckConstraint("quality_state IN ('DEGRADED','UNRESOLVED')"), schema="resilience_v2")
    op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"))
    op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))

def downgrade(**kwargs):
    raise RuntimeError("M5 downgrade disabled; rebuild disposable V2 database explicitly")
