"""M6 pilot readiness contracts and alert facts."""
from alembic import op
import sqlalchemy as sa
revision='m6_0009'; down_revision='m5_0008'
def upgrade(profile, **kwargs):
    u=sa.UUID()
    op.create_table('feed_adapter_contracts',sa.Column('tenant_id',u,nullable=False),sa.Column('contract_id',u,nullable=False),sa.Column('feed_type',sa.Text,nullable=False),sa.Column('schema_version',sa.Text,nullable=False),sa.Column('required_fields',sa.JSON,nullable=False),sa.Column('idempotency_field',sa.Text,nullable=False),sa.Column('status',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','contract_id'),sa.UniqueConstraint('tenant_id','feed_type','schema_version'),sa.CheckConstraint("status IN ('DRAFT','ACTIVE','RETIRED')"),schema='resilience_v2')
    op.create_table('alert_events',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('alert_id',u,nullable=False),sa.Column('alert_type',sa.Text,nullable=False),sa.Column('severity',sa.Text,nullable=False),sa.Column('message',sa.Text,nullable=False),sa.Column('route',sa.Text,nullable=False),sa.Column('state',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','alert_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("severity IN ('INFO','WARNING','CRITICAL')"),sa.CheckConstraint("state IN ('OPEN','ACKNOWLEDGED','CLOSED')"),schema='resilience_v2')
    op.create_table('pilot_gate_results',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('gate_id',u,nullable=False),sa.Column('gate_key',sa.Text,nullable=False),sa.Column('result',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint('tenant_id','gate_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.UniqueConstraint('tenant_id','run_id','gate_key'),sa.CheckConstraint("result IN ('PASS','FAIL','WAIVED')"),schema='resilience_v2')
    op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"))
    op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M6 downgrade disabled; rebuild disposable V2 database explicitly')
