"""M7 cross-border transaction and corridor-risk facts."""
from alembic import op
import sqlalchemy as sa
revision='m7_0010'; down_revision='m6_0009'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('cross_border_obligations',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('cross_border_id',u,nullable=False),sa.Column('obligation_id',u,nullable=False),sa.Column('corridor',sa.Text,nullable=False),sa.Column('origin_country',sa.Text,nullable=False),sa.Column('destination_country',sa.Text,nullable=False),sa.Column('settlement_currency',sa.Text,nullable=False),sa.Column('reporting_currency',sa.Text,nullable=False),sa.Column('local_amount_minor',sa.BigInteger,nullable=False),sa.Column('reporting_amount_minor',sa.BigInteger,nullable=False),sa.Column('fx_rate',sa.Numeric(18,8),nullable=False),sa.Column('cutoff_at',sa.DateTime(timezone=True),nullable=False),sa.Column('compliance_state',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','cross_border_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.ForeignKeyConstraint(['tenant_id','obligation_id'],['resilience_v2.settlement_obligations.tenant_id','resilience_v2.settlement_obligations.obligation_id']),sa.UniqueConstraint('tenant_id','obligation_id'),sa.CheckConstraint("compliance_state IN ('CLEARED','REVIEW','BLOCKED')"),schema='resilience_v2')
 op.create_table('corridor_scenarios',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('scenario_id',u,nullable=False),sa.Column('corridor',sa.Text,nullable=False),sa.Column('scenario_type',sa.Text,nullable=False),sa.Column('fx_shock_pct',sa.Numeric(8,4),nullable=False),sa.Column('cutoff_delay_hours',sa.Integer,nullable=False),sa.Column('compliance_review_rate_pct',sa.Numeric(8,4),nullable=False),sa.Column('impact_state',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','scenario_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("impact_state IN ('LOW','MEDIUM','HIGH')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}"))
 op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M7 downgrade disabled; rebuild disposable V2 database explicitly')
