"""M8 regulatory shock and compliance impact facts."""
from alembic import op
import sqlalchemy as sa
revision='m8_0011'; down_revision='m7_0010'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('regulatory_shocks',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('shock_id',u,nullable=False),sa.Column('regulation_code',sa.Text,nullable=False),sa.Column('shock_type',sa.Text,nullable=False),sa.Column('effective_at',sa.DateTime(timezone=True),nullable=False),sa.Column('reserve_rate_pct',sa.Numeric(8,4),nullable=False),sa.Column('review_rate_pct',sa.Numeric(8,4),nullable=False),sa.Column('restriction_state',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','shock_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),schema='resilience_v2')
 op.create_table('regulatory_impacts',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('impact_id',u,nullable=False),sa.Column('shock_id',u,nullable=False),sa.Column('obligation_id',u,nullable=False),sa.Column('impact_state',sa.Text,nullable=False),sa.Column('reserve_amount_minor',sa.BigInteger,nullable=False),sa.Column('review_required',sa.Boolean,nullable=False),sa.Column('evidence_ref',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','impact_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.ForeignKeyConstraint(['tenant_id','shock_id'],['resilience_v2.regulatory_shocks.tenant_id','resilience_v2.regulatory_shocks.shock_id']),sa.ForeignKeyConstraint(['tenant_id','obligation_id'],['resilience_v2.settlement_obligations.tenant_id','resilience_v2.settlement_obligations.obligation_id']),sa.CheckConstraint("impact_state IN ('UNCHANGED','RESERVED','REVIEW','RESTRICTED')"),schema='resilience_v2')
 op.create_table('regulatory_measures',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('measure_id',u,nullable=False),sa.Column('measure_key',sa.Text,nullable=False),sa.Column('measure_value',sa.Numeric(20,6),nullable=False),sa.Column('unit',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','measure_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.UniqueConstraint('tenant_id','run_id','measure_key'),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}")); op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M8 downgrade disabled; rebuild disposable V2 database explicitly')
