"""M9 merchant risk and forensic intelligence facts."""
from alembic import op
import sqlalchemy as sa
revision='m9_0012'; down_revision='m8_0011'
def upgrade(profile, **kwargs):
 u=sa.UUID()
 op.create_table('merchant_risk_scores',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('score_id',u,nullable=False),sa.Column('merchant_key',sa.Text,nullable=False),sa.Column('exposure_minor',sa.BigInteger,nullable=False),sa.Column('held_count',sa.Integer,nullable=False),sa.Column('concentration_pct',sa.Numeric(8,4),nullable=False),sa.Column('risk_band',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','score_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.UniqueConstraint('tenant_id','run_id','merchant_key'),sa.CheckConstraint("risk_band IN ('LOW','MEDIUM','HIGH','CRITICAL')"),schema='resilience_v2')
 op.create_table('forensic_signals',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('signal_id',u,nullable=False),sa.Column('signal_type',sa.Text,nullable=False),sa.Column('merchant_key',sa.Text,nullable=False),sa.Column('severity',sa.Text,nullable=False),sa.Column('signal_value',sa.Numeric(20,6),nullable=False),sa.Column('explanation',sa.Text,nullable=False),sa.Column('evidence_refs',sa.JSON,nullable=False),sa.PrimaryKeyConstraint('tenant_id','signal_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("severity IN ('INFO','WARNING','HIGH','CRITICAL')"),schema='resilience_v2')
 op.create_table('concentration_metrics',sa.Column('tenant_id',u,nullable=False),sa.Column('run_id',u,nullable=False),sa.Column('metric_id',u,nullable=False),sa.Column('dimension',sa.Text,nullable=False),sa.Column('dimension_value',sa.Text,nullable=False),sa.Column('exposure_minor',sa.BigInteger,nullable=False),sa.Column('share_pct',sa.Numeric(8,4),nullable=False),sa.Column('risk_state',sa.Text,nullable=False),sa.PrimaryKeyConstraint('tenant_id','metric_id'),sa.ForeignKeyConstraint(['tenant_id','run_id'],['resilience_v2.runs.tenant_id','resilience_v2.runs.run_id']),sa.CheckConstraint("risk_state IN ('NORMAL','ELEVATED','CONCENTRATED')"),schema='resilience_v2')
 op.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA resilience_v2 TO {profile.runtime_user}")); op.execute(sa.text(f"REVOKE INSERT, UPDATE, DELETE ON resilience_v2.tenants, resilience_v2.actors, resilience_v2.environment_identity, resilience_v2.alembic_version FROM {profile.runtime_user}"))
def downgrade(**kwargs): raise RuntimeError('M9 downgrade disabled; rebuild disposable V2 database explicitly')
